netsh firewall add allowedprogram "C:\Program Files\Taudem\TauDEM5Exe\AreaD8.exe" AreaD8 ENABLE
netsh firewall add allowedprogram "C:\Program Files\Taudem\TauDEM5Exe\AreaDinf.exe" AreaDinf ENABLE
netsh firewall add allowedprogram "C:\Program Files\Taudem\TauDEM5Exe\D8FlowDir.exe" D8FlowDir ENABLE
netsh firewall add allowedprogram "C:\Program Files\Taudem\TauDEM5Exe\DinfFlowDir.exe" DinfFlowDir ENABLE
netsh firewall add allowedprogram "C:\Program Files\Taudem\TauDEM5Exe\D8FlowPathExtremeUp.exe" D8FlowPathExtremeUp ENABLE
netsh firewall add allowedprogram "C:\Program Files\Taudem\TauDEM5Exe\D8HDistToStrm.exe" D8HDistToStrm ENABLE
netsh firewall add allowedprogram "C:\Program Files\Taudem\TauDEM5Exe\DinfAvalanche.exe" DinfAvalanche ENABLE
netsh firewall add allowedprogram "C:\Program Files\Taudem\TauDEM5Exe\DinfConcLimAccum.exe" DinfConcLimAccum ENABLE
netsh firewall add allowedprogram "C:\Program Files\Taudem\TauDEM5Exe\DinfDecayAccum.exe" DinfDecayAccum ENABLE
netsh firewall add allowedprogram "C:\Program Files\Taudem\TauDEM5Exe\DinfDistDown.exe" DinfDistDown ENABLE
netsh firewall add allowedprogram "C:\Program Files\Taudem\TauDEM5Exe\DinfDistUp.exe" DinfDistUp ENABLE
netsh firewall add allowedprogram "C:\Program Files\Taudem\TauDEM5Exe\DinfFlowDir.exe" DinfFlowDir ENABLE
netsh firewall add allowedprogram "C:\Program Files\Taudem\TauDEM5Exe\DinfRevAccum.exe" DinfRevAccum ENABLE
netsh firewall add allowedprogram "C:\Program Files\Taudem\TauDEM5Exe\DinfTransLimAccum.exe" DinfTransLimAccum ENABLE
netsh firewall add allowedprogram "C:\Program Files\Taudem\TauDEM5Exe\DinfUpDependence.exe" DinfUpDependence ENABLE
netsh firewall add allowedprogram "C:\Program Files\Taudem\TauDEM5Exe\DropAnalysis.exe" DropAnalysis ENABLE
netsh firewall add allowedprogram "C:\Program Files\Taudem\TauDEM5Exe\Gridnet.exe" Gridnet ENABLE
netsh firewall add allowedprogram "C:\Program Files\Taudem\TauDEM5Exe\Lengtharea.exe" LengthArea ENABLE
netsh firewall add allowedprogram "C:\Program Files\Taudem\TauDEM5Exe\MoveOutletsToStreams.exe" MoveOutletsToStreams ENABLE
netsh firewall add allowedprogram "C:\Program Files\Taudem\TauDEM5Exe\PeukerDouglas.exe" PeukerDouglas ENABLE
netsh firewall add allowedprogram "C:\Program Files\Taudem\TauDEM5Exe\PitRemove.exe" PitRemove ENABLE
netsh firewall add allowedprogram "C:\Program Files\Taudem\TauDEM5Exe\SlopeArea.exe" SlopeArea ENABLE
netsh firewall add allowedprogram "C:\Program Files\Taudem\TauDEM5Exe\SlopeAreaRatio.exe" SlopeAreaRatio ENABLE
netsh firewall add allowedprogram "C:\Program Files\Taudem\TauDEM5Exe\SlopeAveDown.exe" SlopeAveDown ENABLE
netsh firewall add allowedprogram "C:\Program Files\Taudem\TauDEM5Exe\Threshold.exe" Threshold ENABLE
netsh firewall add allowedprogram "C:\Program Files\Taudem\TauDEM5Exe\Streamnet.exe" Streamnet ENABLE
netsh firewall add allowedprogram "C:\Program Files\Taudem\TauDEM5Exe\SinmapSI.exe" SinmapSI ENABLE
netsh firewall add allowedprogram "C:\program files\taudem\taudem5exe\gagewatershed.exe" Gagewatershed ENABLE
netsh firewall add allowedprogram "C:\program files\taudem\taudem5exe\twi.exe" TWI ENABLE
netsh firewall add allowedprogram "C:\program files\taudem\taudem5exe\connectdown.exe" connectdown ENABLE
netsh firewall add allowedprogram "C:\program files\microsoft hpc pack 2012\bin\smpd.exe" smpd ENABLE
